# ====================================================================================================================================
# @file       left_laser_driver.yaml
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Tuesday, 22nd March 2022 3:12:52 am
# @modified   Friday, 1st July 2022 8:03:34 pm
# @project    engineering-thesis
# @brief      Default configuration for the velmwheel_laser_driver of the left LIDAR sensor
#    
#    
# @note Configuration has been based on the <sick_scan>/launch/sick_lms_1xx.launch launch file
# @copyright Krzysztof Pierczyk Â© 2022
# ====================================================================================================================================

/**:

    # Parameters
    ros__parameters:

        # Hostname of the sensor
        hostname: '192.168.0.2'
        
        # If true, the internal Software PLL is fored to sync the scan generation time stamp to a system timestamp
        sw_pll_only_publish: true

        # Whether to start ROS service for cola commands
        start_services: True
        # Whether to activate field monitoring by lferec messages
        activate_lferec: True
        # Whether to activate field monitoring by lidoutputstate messages
        activate_lidoutputstate: True
        # Whether to activate field monitoring by lidinputstate messages
        activate_lidinputstate: True
        # Set range of scans intensities to infinity, if intensity < min_intensity (default: 0)
        min_intensity: 0.0
        
        # Supported values are "0.25" and "0.50"
        ang_res: 0.5
        # Supported values are "25" and "50"
        scan_freq: 50.0

        # -------------------------------------------------------------------------------------------------------
        # @note : angular resolution and scanning frequency of a LMS111 can be configured by parameter "ang_res" 
        #   (values "0.25" or "0.5") and "scan_freq"  (values "25" or "50"). After setting "ang_res" and 
        #   "scan_freq", it takes ca. 30 seconds until the pointcloud is published. Recommendation: It is 
        #   recommended to specify the desired angular resolution and scan rate in this launch file. In this 
        #   case, it is necessary to wait approx. 30 sec. until the Lidar changes to status "OK". Alternatively,
        #   these settings can be configured in SOPAS-ET, transferred to the EEProm of the lidar and then 
        #   permanently stored. In this case, the explicit specification of scan rate and angular resolution
        #   can be omitted and the waiting time can be avoided. -
        # -------------------------------------------------------------------------------------------------------

        # Enable message monitoring with reconnect+reinit in case of timeouts, default: true
        message_monitoring_enabled: True
        # 5 sec read timeout in operational mode (measurement mode), default: 5000 milliseconds
        read_timeout_millisec_default: 5000
        # 120 sec read timeout during startup (sensor may be starting up, which can take up to 120 sec.), default: 120000 milliseconds
        read_timeout_millisec_startup: 120000
        # 150 sec pointcloud timeout, ros node will be killed if no point cloud published within the last 150 sec., default: 150000 milliseconds
        read_timeout_millisec_kill_node: 150000
        # Default password for client authorization
        client_authorization_pw: F4724744
