# ====================================================================================================================================
# @file       left_laser_driver.yaml
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Tuesday, 22nd March 2022 3:12:52 am
# @modified   Thursday, 7th July 2022 6:29:54 pm
# @project    engineering-thesis
# @brief      Default configuration for the velmwheel_laser_driver of the left LIDAR sensor
#    
#    
# @copyright Krzysztof Pierczyk Â© 2022
# ====================================================================================================================================

/**:

    # Parameters
    ros__parameters:

        # IP of the host
        hostname: '192.168.0.1'
        # IP of the sensor
        devicename: '192.168.0.2'

        # Scan frequency (25 or 50)
        scan_frequency: 50
        # Angular resolution (0.25 or 0.5)
        angular_resolution: 0.5

        # NTP usage
        use_ntp: true
